//tag::ref-doc[]
= Twitter Friendships Source

Returns a cursored collection of user objects either for the https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-list[users following the specified user] (`followers`) or for https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-list[every user the specified user is following] (`friends`).

The `twitter.friendships.source.type` property allow to select between both types.

TIP: Rate limit: 15 requests per 30 min window. ~ 1 req/ 2 min

== Options

//tag::configuration-properties[]
$$twitter.friendships.source.count$$:: $$The number of users to return per page, up to a maximum of 200. Defaults to 20.$$ *($$Integer$$, default: `$$200$$`)*
$$twitter.friendships.source.include-user-entities$$:: $$The user object entities node will be disincluded when set to false.$$ *($$Boolean$$, default: `$$true$$`)*
$$twitter.friendships.source.poll-interval$$:: $$API request poll interval in milliseconds. Must be aligned with used APIs rate limits (~ 1 req/ 2 min).$$ *($$Integer$$, default: `$$121000$$`)*
$$twitter.friendships.source.screen-name$$:: $$The screen name of the user for whom to return results.$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.friendships.source.skip-status$$:: $$When set to true, statuses will not be included in the returned user objects.$$ *($$Boolean$$, default: `$$false$$`)*
$$twitter.friendships.source.type$$:: $$Selects between followers or friends APIs.$$ *($$FriendshipsRequestType$$, default: `$$<none>$$`, possible values: `followers`,`friends`)*
$$twitter.friendships.source.user-id$$:: $$The ID of the user for whom to return results.$$ *($$Long$$, default: `$$<none>$$`)*
//end::configuration-properties[]

//end::ref-doc[]

== Build

Build involves two-stages. First build the apps and generate the binder specific app starters projects:
```
$ ./mvnw clean install -PgenerateApps
```

You can find the corresponding binder based projects in the `apps` subfolder. You can then cd into the apps folder:

```
$ cd apps
```
and build all binder projects
```
$ ./mvnw clean package
```

== Examples

```
java -jar twitter-friendships-source.jar ... use the properties TODO
```

And here is a example pipeline that uses twitter-friendships:

```
twitter-friendships-stream= TODO
```
