//tag::ref-doc[]
= Twitter Trend Location Processor

Retrieve a full or nearby locations list of trending topics by location.

If the `latitude`, `longitude` parameters are NOT provided the processor performs the https://developer.twitter.com/en/docs/trends/locations-with-trending-topics/api-reference/get-trends-available[Trends Available API] and returns the locations that Twitter has trending topic information for.

If the `latitude`, `longitude` parameters are provided the processor performs the https://developer.twitter.com/en/docs/trends/locations-with-trending-topics/api-reference/get-trends-closest[Trends Closest API] and returns the locations that Twitter has trending topic information for, closest to a specified location.

Response is an array of `locations` that encode the location's WOEID and some other human-readable information such as a canonical name and country the location belongs in.

== Options

//tag::configuration-properties[]
//end::configuration-properties[]

//end::ref-doc[]

== Build

Build involves two-stages. First build the apps and generate the binder specific app starters projects:
```
$ ./mvnw clean install -PgenerateApps
```

You can find the corresponding binder based projects in the `apps` subfolder. You can then cd into the apps folder:

```
$ cd apps
```
and build all binder projects
```
$ ./mvnw clean package
```

== Examples

```
java -jar twitter-trend-location-processor.jar ... use the properties TODO
```

And here is a example pipeline that uses twitter-trend-location:

```
twitter-trend-location-stream= TODO
```
