//tag::ref-doc[]
= Twitter Users Processor

Retrieves users either by list of use ids and/or screen-names (https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup[Users Lookup API]) or by text search query (https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-search[Users Search API]).
The SpEL expressions are used to compute the query parameters from the input message. Use the single quoted literals to set static values (e.g. user-id: '6666, 9999, 10000').

Use `twitter.users.type` property allow to select the query approaches.

* https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup[Users Lookup API] - Returns fully-hydrated user objects for up to 100 users per request, as specified by comma-separated values passed to the `userId` and/or `screenName` parameters. Rate limits: (300 requests / 15-min window)
* https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-search[Users Search API] - Relevance-based search interface to public user accounts on Twitter.
Querying by topical interest, full name, company name, location, or other criteria. Exact match searches are not supported. Only the first 1,000 matching results are available. Rate limits:(900 requests / 15-min window)

== Options

//tag::configuration-properties[]
$$twitter.users.lookup.screen-name$$:: $$A comma separated list of screen names, up to 100 are allowed in a single request. You are strongly encouraged to use a POST for larger (up to 100 screen names) requests.$$ *($$Expression$$, default: `$$<none>$$`)*
$$twitter.users.lookup.user-id$$:: $$A comma separated list of user IDs, up to 100 are allowed in a single request. You are strongly encouraged to use a POST for larger requests.$$ *($$Expression$$, default: `$$<none>$$`)*
$$twitter.users.search.page$$:: $$Specifies the page of results to retrieve.$$ *($$Integer$$, default: `$$3$$`)*
$$twitter.users.search.query$$:: $$The search query to run against people search.$$ *($$Expression$$, default: `$$<none>$$`)*
$$twitter.users.type$$:: $$Perform search or lookup type of search.$$ *($$UserQueryType$$, default: `$$<none>$$`, possible values: `search`,`lookup`)*
//end::configuration-properties[]

//end::ref-doc[]

== Build

Build involves two-stages. First build the apps and generate the binder specific app starters projects:
```
$ ./mvnw clean install -PgenerateApps
```

You can find the corresponding binder based projects in the `apps` subfolder. You can then cd into the apps folder:

```
$ cd apps
```
and build all binder projects
```
$ ./mvnw clean package
```

== Examples

```
java -jar twitter-users-processor.jar ... use the properties TODO
```

And here is a example pipeline that uses twitter-users:

```
twitter-users-stream= TODO
```
