//tag::ref-doc[]
= Twitter Friendships Sink

Allows creating `follow`, `unfollow` and `update` relationships with specified `userId` or `screenName`.
The `twitter.friendships.sink.type` property allows to select the desired friendship operation.

* https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/post-friendships-create[Friendships Create API] - Allows the authenticating user to follow (friend) the user specified in the ID parameter.
Actions taken in this method are asynchronous.
Changes will be eventually consistent.
* https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/post-friendships-update[Friendships Update API] - Enable or disable Retweets and device notifications from the specified user.
* https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/post-friendships-destroy[Friendships Destroy API] - Allows the authenticating user to unfollow the user specified in the ID parameter.

SpEL expressions are used to compute the request parameters from the input message.
Every operation type has its own parameters.


== Options

//tag::configuration-properties[]
$$twitter.friendships.sink.create.follow$$:: $$The ID of the user to follow (boolean).$$ *($$Expression$$, default: `$$'true'$$`)*
$$twitter.friendships.sink.screen-name$$:: $$The screen name of the user to follow (String).$$ *($$Expression$$, default: `$$<none>$$`)*
$$twitter.friendships.sink.type$$:: $$Type of Friendships request.$$ *($$Expression$$, default: `$$'create'$$`)*
$$twitter.friendships.sink.update.device$$:: $$Enable/disable device notifications from the target user.$$ *($$Expression$$, default: `$$'true'$$`)*
$$twitter.friendships.sink.update.retweets$$:: $$Enable/disable Retweets from the target user.$$ *($$Expression$$, default: `$$'true'$$`)*
$$twitter.friendships.sink.user-id$$:: $$The ID of the user to follow (Integer).$$ *($$Expression$$, default: `$$<none>$$`)*
//end::configuration-properties[]

//end::ref-doc[]

== Build

Build involves two-stages. First build the apps and generate the binder specific app starters projects:
```
$ ./mvnw clean install -PgenerateApps
```

You can find the corresponding binder based projects in the `apps` subfolder. You can then cd into the apps folder:

```
$ cd apps
```
and build all binder projects
```
$ ./mvnw clean package
```

== Examples

```
java -jar twitter-friendships-sink.jar ... use the properties TODO
```

And here is a example pipeline that uses twitter-friendships:

```
twitter-friendships-stream= TODO
```
